// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6V7aQ5C1KkWmEo5wf6tFUCg_p-A0TXxE',
    appId: '1:188040759599:web:fd6e1788ce6f57f60ab9da',
    messagingSenderId: '188040759599',
    projectId: 'invite-401215',
    authDomain: 'invite-401215.firebaseapp.com',
    storageBucket: 'invite-401215.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbFb8YTfMqpJQXd7DfF4HYhsWinxuIxOA',
    appId: '1:188040759599:android:b190900de0a775b80ab9da',
    messagingSenderId: '188040759599',
    projectId: 'invite-401215',
    storageBucket: 'invite-401215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGoROgm6Iut7CweSgDL777gJE8C4IxeI',
    appId: '1:188040759599:ios:f2cd71214abbf50b0ab9da',
    messagingSenderId: '188040759599',
    projectId: 'invite-401215',
    storageBucket: 'invite-401215.appspot.com',
    iosBundleId: 'com.example.invite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGoROgm6Iut7CweSgDL777gJE8C4IxeI',
    appId: '1:188040759599:ios:5d9664d875271f0c0ab9da',
    messagingSenderId: '188040759599',
    projectId: 'invite-401215',
    storageBucket: 'invite-401215.appspot.com',
    iosBundleId: 'com.example.invite.RunnerTests',
  );
}
